CREATE TABLE PERSON (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	firstName varchar(255) not null,
	lastName varchar(255) not null
);

create sequence person_sequence start with 1 increment by 1;

insert into PERSON (firstName, lastName) values ('Rob', 'Rong');
